FROM scratch AS ctx
COPY build_files /
COPY rpms /rpms

FROM @BASE_IMAGE@

COPY system_files/ /
COPY --from=ctx /rpms /rpms

RUN rm /opt && mkdir /opt

RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /ctx/build.sh && \
    /ctx/install-apps.sh && \
    /ctx/opensnitch.sh && \
    /ctx/fix-opt.sh && \
    /ctx/build-initramfs.sh && \
    /ctx/remove-packages.sh && \
    /ctx/cleanup.sh

RUN bootc container lint
RUN echo "kokoplay" > /etc/hostname
