name: Cleanup Packages
on:
  schedule:
    - cron: '0 12 * * 1'  # Runs daily at 8 AM
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old package versions
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'kokoplay'
          package-type: 'container'
          delete-only-untagged-versions: 'false'
          min-versions-to-keep: 40
          token: ${{ secrets.GITHUB_TOKEN }}
