name: Cleanup Packages
on:
  schedule:
    - cron: '0 8 * * *'  # Runs daily at 8 AM
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old package versions
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'kokoplay'
          package-type: 'container'
          exclude-tags: .*latest.*
          min-versions-to-keep: 20
          token: ${{ secrets.GITHUB_TOKEN }}
