name: Cleanup Packages
on:
  schedule:
    - cron: '0 12 * * 1'  # Runs every Monday at 12:00      
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package-name: [kokoplay, kokoplay-dev, kokoplay-nvidia, kokoplay-nvidia-open]
    steps:
      - name: Delete old package versions
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ matrix.package-name }}
          package-type: 'container'
          delete-only-untagged-versions: 'false'
          min-versions-to-keep: 40
          token: ${{ secrets.GITHUB_TOKEN }}
