name: Push Artifact Hub Metadata
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install ORAS
        run: |
          mkdir -p oras-install
          curl -sSLO https://github.com/oras-project/oras/releases/download/v1.3.0/oras_1.3.0_linux_amd64.tar.gz
          tar -xzf oras_1.3.0_linux_amd64.tar.gz -C oras-install
          sudo mv oras-install/oras /usr/local/bin
          rm -rf oras_1.3.0_linux_amd64.tar.gz oras-install

      - name: Push artifacthub-repo.yml
        run: |
          oras push ghcr.io/kokodroid/kokoplay:artifacthub.io \
            --config /dev/null:application/vnd.cncf.artifacthub.config.v1+yaml \
            artifacthub-repo.yml:application/vnd.cncf.artifacthub.repository-metadata.layer.v1.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   